from enum import Enum


class Status(Enum):
    PENDING = 0
    ACTIVE = 1
    PREEMPTED = 2
    SUCCEEDED = 3
    ABORTED = 4
    REJECTED = 5
    PREEMPTING = 6
    RECALLING = 7
    RECALLED = 8
    LOST = 9


class FeedbackStatus(Enum):
    UNDEFINED = 0
    UNDEFINED_MODULE = 0
    FAILED = 1
    FMS = 1
    SMART_WHEEL = 1
    MANEUVER_NAVIGATION = 2
    FLOCK = 2
    SUCCEEDED = 2
    INITIALIZED = 3
    ROBOT = 3
    ROUTE_NAVIGATION = 3
    COMPONENT = 4
    CONFIGURING = 4
    DOCKING_MECHANISM = 4
    MOBIDIK_COLLECTION = 5
    READY = 5
    RUNNING = 6
    ELEVATOR_ACTION = 6
    TASK_EXECUTOR = 7
    RECOVERING = 7
    STOPPED = 8
    DOCKING_SEQUENCE_SUCCEEDED = 9
    NAVIGATION_IN_PROGRESS = 9
    DOCKING_SEQUENCE_FAILED = 10
    GOAL_REACHED = 10
    COUPLING_SUCCEEDED = 11
    GOAL_NOT_REACHABLE = 11
    WAITING = 11
    COUPLING_FAILED = 12
    ENTERING = 12
    DECOUPLING_SUCCEEDED = 13
    RIDING_ELEVATOR = 13
    DECOUPLING_FAILED = 14
    EXITING = 14
    UNDOCKING_SEQUENCE_SUCCEEDED = 15
    WAITING_POINT_REACHED = 15
    DOOR_OPENED = 16
    UNDOCKING_SEQUENCE_FAILED = 16
    MOBIDIK_DETECTED = 17
    ENTERING_ELEVATOR = 17
    ENTERED_ELEVATOR = 18
    MULTIPLE_MOBIDIK_CANDIDATES_DETECTED = 18
    NO_MOBIDIK_DETECTED = 19
    DESTINATION_FLOOR_REACHED = 19
    DOCKING_AREA_EMPTY = 20
    EXITED_ELEVATOR = 20
    PRE_DOCK_POSITION_UNREACHABLE = 21
    POST_DOCK_POSITION_UNREACHABLE = 22
    MOBIDIK_UNREACHABLE = 23
    ALIGNMENT_TO_MOBIDIK_FAILED = 24
    DOCKED_TO_WRONG_SIDE = 25
    MOBIDIK_CAN_NOT_BE_PULLED = 26
    ACTIVE_SEARCH_MODE = 27
    WAITING_FOR_ELEVATOR_FAILED = 29
    WAITING_POINT_UNREACHABLE = 30
    ELEVATOR_WAIT_TIMEOUT = 31
    ELEVATOR_ENTERING_FAILED = 32
    ELEVATOR_RIDE_TIMEOUT = 33
    ELEVATOR_RIDE_MAP_CHANGE_FAILURE = 34
    ELEVATOR_EXITING_FAILED = 35
    ELEVATOR_ACTION_PREEMPTED = 36
